name: End to End(E2E) Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main
      - "!renovate/**"
  workflow_dispatch:

jobs:
  e2e_tests:
    if: "!startsWith(github.event.pull_request.title, 'WIP:')"
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:16.14.2-slim
    steps:
      - name: Checkout 🚩
        uses: actions/checkout@v3

      # - name: Install cURL ⬇️
      #   run: |
      #     apt update
      #     apt install curl -y

      # - name: Install hostess 🪶
      #   run: |
      #     curl -Lso /usr/bin/hostess https://github.com/cbednarski/hostess/releases/latest/download/hostess_linux_amd64
      #     chmod +x /usr/bin/hostess


      # - name: Add test API hostname/IP via hostess ⚙️
      #   run: hostess add thissiteisunexist.com 127.0.0.1

      - name: Configure host for Test API ⚙️
        run: | 
          echo "thissiteisunexist.com 127.0.0.1" >> /etc/hosts
          cat /etc/hosts

      - name: Get yarn cache directory path 🛣️
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn dependencies 📦
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # - name: Change owner of /github/home/ 👤
      #   run: chown -R root:root /github/home/

      - name: Install dependencies 📦
        run: yarn install --immutable

      - name: Build the app 🏗️
        run: yarn build

      - name: Run E2E tests 🧪💻
        run: yarn e2e:run
